# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e19a556a1402be37a01ef225441644aaa33d5334cbeef015aca7b7ccfb6bb1fa1a9310f3daaf51852e90e96bf155def0177fe74cc3d8648e37885e1432d1901

test:
  secret_key_base: 009326449d931762ff7acf8c263ba51528c025694ef8f9371ddba99a262880bebe6023d340160e746e67f6c87649f42af83acb6d0696ccc21c4ef4182632e8f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
